$(window).on("load",function(){$(".loader").fadeOut(800);$(".side-menu").removeClass("opacity-0");var a=this.textContent=atob("aW5mbw==")+"@cybernetica"+String.fromCharCode(46)+"com"+String.fromCharCode(46)+atob("YXU=");$(".email_reveal").text(a);$(".email_reveal").attr("href","mailto:"+a);$(".phone_reveal").text(atob("IDAyIDg1OTMgNDY5OQ=="));$(".phone_reveal_int").text(atob("IDA2MTIgODU5MyA0Njk5"))});
function enquiry(a){1===a?$("message1").text("SMB: "):2===a?$("message1").text("SME: "):3===a&&$("message1").text("Enterprise: ")}
jQuery(function(a){function E(){function b(){var h=Math.round(p.outerWidth())*p.length;l.outerWidth()<=h?(d=!0,f.addClass("accordion-mod")):(d=!1,f.removeClass("accordion-mod"))}var c=a(window),d=!0,f=a(".tab-to-accordion"),n=f.find(".tab-container").children("div[id]"),l=f.find(".tabset-list"),p=l.find("li"),q=l.find("a"),z=l.find(".active").children().attr("href");(function(){a(q).each(function(){var h=a(this),k=h.parent().hasClass("active"),v=h.attr("href"),F=a(v);if(k){var G=v;F.show()}k=h.clone();
h=h.attr("href");G?k.insertBefore(h).wrap('<div class="accordion-item active"></div>'):k.insertBefore(h).wrap('<div class="accordion-item"></div>')})})();b();(function(){n.hide();a(z).show();a(f).on("click",'a[href^="#tab"]',function(h){h.preventDefault();var k=a(this).attr("href");h=a(k);k=f.find('a[href="'+k+'"]');a('a[href^="#tab"]').parent().removeClass("active");k.parent().addClass("active");d?(n.stop().slideUp(500),h.stop().slideDown(500)):(n.hide(),h.show())})})();(function(){var h=location.hash,
k=a(h),v=f.find('a[href="'+h+'"]');0<a(h).length&&(a('a[href^="#tab"]').parent().removeClass("active"),v.parent().addClass("active"),n.hide(),k.show(),c.scrollTop(k.offset().top).scrollLeft(k.offset().left))})();c.on("resize orientationchange",b)}function A(){setTimeout(function(){g.find(".owl-item").first().addClass("synced")},300)}var m=a(window),e=a("body"),H=a("html, body");a('[data-toggle="tooltip"]').tooltip();a("#lnkDesign, #lnkCode, #lnkTesting, #lnkMonitoring").on("click",function(){var b=
a(this)[0].id,c=0;"lnkTesting"===b?(c=a(".testing").offset().top,c-=45):"lnkCode"===b?(c=a(".implementation").offset().top,c-=45):"lnkDesign"===b?(c=a(".design").offset().top,c-=45):"lnkMonitoring"===b&&(c=a(".monitoring").offset().top,c-=205);a("html,body").animate({scrollTop:c},1200)});a("#submit_btn1 , #submit_btn").on("click",function(){var b=a(this)[0];grecaptcha.ready(function(){grecaptcha.execute("6LdeRP8UAAAAAHZ_cTRf95cxUg3XJzuJdIXEFzKk",{action:"submit"}).then(function(c){document.getElementById("recaptchaResponse").value=
c;var d=a("#name1").val(),f=a("#email1").val(),n=a("#message1").val();if("submit_btn"===b.id){var l=a("#result");n=a("#companyName").val();d=a("#userName").val();f=a("#email").val()}else l=a("#result1");var p=!0;""===d&&(p=!1);""===f&&(p=!1);""===n&&(p=!1);if(p)c={name:d,email:f,message:n,recaptcha_response:c},a.post("/contact",c,function(z){}).done(function(){q='<div class="alert-success" style="padding:10px; margin-bottom:25px;">Thank you for your message, we will get back to you soon.</div>';a(".getin_form input").val("");
a(".getin_form textarea").val("");l.slideUp("fast").html(q).slideDown()}).fail(function(){q='<div class="alert-danger" style="padding:10px; margin-bottom:25px;">Please verify your form and try again</div>';l.slideUp("fast").html(q).slideDown()});else{var q='<div class="alert-danger" style="padding:10px; margin-bottom:25px;">Please provide the missing fields.</div>';l.slideUp("fast").html(q).slideDown()}})})});var I=function(){var b=a("#rattingIcon .fa-star.fas");b.addClass("scale-star");setTimeout(function(){b.removeClass("scale-star")},
180)},r=a("#ratingText"),J=function(b){r.addClass("scale-price");setTimeout(function(){r.removeClass("scale-price");switch(b){case 0:r.text("Poor!");break;case 1:r.text("Average!");break;case 2:r.text("Good!");break;case 3:r.text("Very Good!");break;case 4:r.text("Excellent!")}},180)};a("#rattingIcon .fa-star").on("click",function(){var b=a(this).index();a(this).addClass("fas").removeClass("far");a(this).prevAll().addClass("fas").removeClass("far");a(this).nextAll().addClass("far").removeClass("fas");
I();J(b)});a(e).append('<a href="#" class="back-top"><i class="fa fa-angle-up"></i></a>');var y=a("a.back-top");m.on("scroll",function(){700<m.scrollTop()?y.addClass("back-top-visible"):y.removeClass("back-top-visible")});y.on("click",function(){H.animate({scrollTop:0},700);return!1});a("a.pagescroll").on("click",function(b){b.preventDefault();b=a(this.hash).offset().top;a(this).hasClass("scrollupto")&&(b-=45);a("html,body").animate({scrollTop:b},1200)});a(".dropdown").on("mouseenter",function(){var b=
a(this).find(".dropdown-menu"),c=b.offset().left,d=b.width(),f=a(window).width();c+d>f?b.addClass("right-show"):c+2*d<f&&b.removeClass("right-show")});var K=a("header").outerHeight();e=a("nav.navbar");e.not(".fixed-bottom").hasClass("static-nav")&&(m.scroll(function(){var b=m.scrollTop(),c=a(".static-nav"),d=a(".section-nav-smooth");250<b?(c.addClass("fixedmenu"),d.css("margin-top",K)):(c.removeClass("fixedmenu"),d.css("margin-top",0));125<b?a(".header-with-topbar nav").addClass("mt-0"):a(".header-with-topbar nav").removeClass("mt-0")}),
a(function(){m.scrollTop()>=a(window).height()&&a(".static-nav").addClass("fixedmenu")}));if(e.hasClass("fixed-bottom")){var L=a(".fixed-bottom").offset().top,B=m.scrollTop();a(window).scroll(function(){a(window).scrollTop()>L?a(".fixed-bottom").addClass("fixedmenu"):a(".fixed-bottom").removeClass("fixedmenu");260>a(window).scrollTop()?a(".fixed-bottom").addClass("menu-top"):a(".fixed-bottom").removeClass("menu-top")});a(function(){230>B?a(".fixed-bottom").addClass("menu-top"):a(".fixed-bottom").removeClass("menu-top");
B>=a(window).height()&&a(".fixed-bottom").addClass("fixedmenu")})}e=a("#sidemenu_toggle");var w=a(".side-menu");e.length&&(e.on("click",function(){a("body").addClass("overflow-hidden");w.addClass("side-menu-active");a(function(){setTimeout(function(){a("#close_side_menu").fadeIn(300)},300)})}),a("#close_side_menu , #btn_sideNavClose , .side-nav .nav-link.pagescroll").on("click",function(){a("body").removeClass("overflow-hidden");w.removeClass("side-menu-active");a("#close_side_menu").fadeOut(200);
a(function(){setTimeout(function(){a(".sideNavPages").removeClass("show");a(".fas").removeClass("rotate-180")},400)})}),a(document).keyup(function(b){27===b.keyCode&&w.hasClass("side-menu-active")&&(a("body").removeClass("overflow-hidden"),w.removeClass("side-menu-active"),a("#close_side_menu").fadeOut(200),C.tooltipster("close"),a(function(){setTimeout(function(){a(".sideNavPages").removeClass("show");a(".fas").removeClass("rotate-180")},400)}))}));a(".collapsePagesSideMenu").on("click",function(){a(this).children().toggleClass("rotate-180")});
var D=function(){var b=a(".full-screen");b.css("height",m.height());b.css("width",m.width())};D();m.resize(function(){D()});a(".progress").each(function(){a(this).appear(function(){a(this).animate({opacity:1,left:"0px"},500);var b=jQuery(this).find(".progress-bar").attr("data-value");a(this).find(".progress-bar").animate({width:b+"%"},500)})});a(function(){E()});a("#particles-js").length&&particlesJS("particles-js",{particles:{number:{value:100,density:{enable:!0,value_area:800}},color:{value:"#ffffff"},
shape:{type:"circle",stroke:{width:0,color:"#000000"},polygon:{nb_sides:5},image:{src:"img/github.svg",width:100,height:100}},opacity:{value:.5,random:!1,anim:{enable:!1,speed:1,opacity_min:.1,sync:!1}},size:{value:5,random:!0,anim:{enable:!1,speed:40,size_min:.1,sync:!1}},line_linked:{enable:!1,distance:150,color:"#ffffff",opacity:.4,width:1},move:{enable:!0,speed:2,direction:"none",random:!1,straight:!1,out_mode:"bounce",attract:{enable:!1,rotateX:600,rotateY:1200}}},interactivity:{detect_on:"canvas",
events:{onhover:{enable:!0,mode:"grab"},onclick:{enable:!0,mode:"bubble"},resize:!0},modes:{grab:{distance:150,line_linked:{opacity:1}},bubble:{distance:150,size:12,duration:.2,opacity:.6,speed:10},repulse:{distance:150},push:{particles_nb:1},remove:{particles_nb:2}}},retina_detect:!0});e=a("#morph-text");e.length&&e.Morphext({animation:"flipInX",separator:",",speed:3500,complete:function(){}});var C=a(".tooltip");a(function(){C.tooltipster({plugins:["follower"],anchor:"bottom-right",offset:[0,0],
animation:"fade",content:"Click Here To Close or Press ESC!",delay:20,theme:"tooltipster-light",repositionOnScroll:!0})});a(".wow").length&&567<=a(window).outerWidth()&&(new WOW({boxClass:"wow",animateClass:"animated",offset:0,mobile:!1,live:!0})).init();992<a(window).width()?(a(".parallax").parallaxie({speed:.55,offset:0}),a(".parallax.parallax-slow").parallaxie({speed:.31})):576>a(window).width()?(a("#pagepiling #submit_btn").on("click",function(){a("#pagepiling #result").remove()}),a("#pagepiling .para-opacity").addClass("opacity-5")):
a("#pagepiling .para-opacity").removeClass("opacity-5");a(window).resize(function(){576>a(window).width()?a("#pagepiling .para-opacity").addClass("opacity-5"):a("#pagepiling .para-opacity").removeClass("opacity-5")});a(".Pricing-toggle-button").on("click",function(){var b=!0;a(this).hasClass("month")&&(b=!1);a(this).hasClass("active")||(a(".pricing-price .pricing-currency").each(function(){var c=a(this).text();c=c.substring(1,c.length);c=b?9*c:c/9;c=c.toFixed(2);c="$"+c;M(a(this),c)}),a(".pricing-price .pricing-duration").each(function(){b?
a(this).text("year"):a(this).text("month")}),a(this).addClass("active").siblings().removeClass("active"))});var M=function(b,c){var d=a(".pricing-price");d.addClass("scale-price");setTimeout(function(){b.text(c);d.removeClass("scale-price")},200)};a(".pricing-item").on("mouseenter",function(){a(".pricing-item").removeClass("active");a(this).addClass("active")}).on("mouseleave",function(){a(".pricing-item").removeClass("active");a(".pricing-item.selected").addClass("active")});a("[data-fancybox]").fancybox({transitionIn:"elastic",
transitionOut:"elastic",speedIn:600,speedOut:200,buttons:"slideShow fullScreen thumbs share zoom close".split(" ")});a("#partners-slider").owlCarousel({items:5,autoplay:1500,smartSpeed:1500,autoplayHoverPause:!0,slideBy:1,loop:!0,margin:30,dots:!1,nav:!1,responsive:{1200:{items:5},991:{items:4},767:{items:3},480:{items:2},0:{items:1}}});a("#testimonial-slider").owlCarousel({items:1,autoplay:!1,autoplayHoverPause:!0,mouseDrag:!1,loop:!0,margin:30,animateIn:"fadeIn",animateOut:"fadeOut",dots:!1,nav:!0,
navText:["<i class='fas fa-angle-left'></i>","<i class='fas fa-angle-right'></i>"],responsive:{980:{items:1},600:{items:1},320:{items:1}}});a("#carousel-gallery-detail").owlCarousel({items:1,autoplay:!1,mouseDrag:!0,loop:!0,margin:0,dots:!1,nav:!0,responsive:{980:{items:1},600:{items:1},320:{items:1}}});a("#testimonial-main-slider").owlCarousel({items:3,autoplay:2500,autoplayHoverPause:!0,loop:!0,margin:0,dots:!0,nav:!1,responsive:{1280:{items:3},980:{items:3},600:{items:2},320:{items:1}}});a("#price-slider").owlCarousel({items:3,
autoplay:!1,loop:!1,margin:0,padding:0,dots:!0,nav:!1,responsive:{1280:{items:3},980:{items:3},600:{items:2},0:{items:1}}});a("#ourteam-slider").owlCarousel({items:4,margin:0,dots:!1,nav:!1,responsive:{1280:{items:4},768:{items:3},520:{items:2},0:{items:1}}});a("#app-slider").owlCarousel({items:1,loop:!0,dots:!1,nav:!1,animateOut:"fadeOut",animateIn:"fadeIn",autoplay:!1,autoplayTimeout:5E3,responsive:{1280:{items:1},600:{items:1},320:{items:1}}});a(".app-slider-lock-btn").on("click",function(){a(".app-slider-lock").fadeToggle(600)});
a("#services-slider").owlCarousel({autoplay:!1,autoplayTimeout:3E3,autoplayHoverPause:!0,smartSpeed:1200,loop:!0,nav:!1,navText:!1,dots:!1,mouseDrag:!0,touchDrag:!0,center:!0,responsive:{0:{items:1},640:{items:3}}});a("#service-detail").owlCarousel({autoplay:!0,autoplayTimeout:3E3,autoplayHoverPause:!0,smartSpeed:1200,loop:!0,nav:!1,dots:!1,mouseDrag:!0,touchDrag:!0,margin:15,responsive:{0:{items:1},640:{items:2}}});a(".owl-blog-item").owlCarousel({loop:!0,dots:!1,items:1,nav:!0,navText:["<i class='fas fa-long-arrow-alt-left'></i>",
"<i class='fas fa-long-arrow-alt-right'></i>"]});e=a("#shop-dual-carousel");var t=a("#syncCarousel.owl-carousel");if(e){e.append('<div class="owl-carousel carousel-shop-detail-inner owl-theme" id="syncChild"></div>');e=t.find(".item").length-1;for(var u="",N=a("#syncChild"),x=0;x<=e;x++)u=t.find(".item").eq(x).find("img").attr("src"),N.append("\x3c!-- Item "+(x+1)+'--\x3e<div class="item"><img src="'+u+'" alt=""></div>')}var g=a("#syncChild.owl-carousel");t.owlCarousel({singleItem:!0,items:1,dots:!1,
slideSpeed:1E3,mouseDrag:!1,nav:!0,pagination:!1,afterAction:A(),responsiveRefreshRate:200});g.owlCarousel({items:4,pagination:!1,margin:0,dots:!1,afterAction:A()});t.on("click",".owl-next",function(){var b=g.find(".owl-item.active:first").index(),c=g.find(".owl-item.active:last").index(),d=g.find(".owl-item.active.synced").index(),f=g.find(".owl-item.synced").index();if(-1===d)if(b>f)for(;b>f;)g.trigger("prev.owl.carousel"),f++;else{if(b<f)for(;b<f;)g.trigger("next.owl.carousel"),f--}else d===c&&
g.trigger("next.owl.carousel");g.find(".owl-item.synced").next().addClass("synced").siblings().removeClass("synced")});t.on("click",".owl-prev",function(){var b=g.find(".owl-item.active:first").index(),c=g.find(".owl-item.active.synced").index(),d=g.find(".owl-item.synced").index();if(-1===c)if(b>d)for(;b>d-2;)g.trigger("prev.owl.carousel"),d++;else{if(b<d)for(;b<d-2;)g.trigger("next.owl.carousel"),d--}else c===b&&g.trigger("prev.owl.carousel");g.find(".owl-item.synced").prev().addClass("synced").siblings().removeClass("synced")});
g.on("click",".owl-item",function(){var b=a(this).index();t.trigger("to.owl.carousel",b,300);a(this).siblings().removeClass("synced");a(this).addClass("synced")});a("#syncCarousel [data-fancybox]").fancybox({transitionIn:"elastic",transitionOut:"elastic",speedIn:600,speedOut:200,buttons:"slideShow fullScreen thumbs share download zoom close".split(" "),afterShow:function(){var b=this.index;a(g).add(t).trigger("to.owl.carousel",b,300);a("#syncChild .owl-item").removeClass("synced").eq(b).addClass("synced")}});
a("#syncCarousel .item").on("mousemove",function(b){a(this).find("img").css({"transform-origin":(b.pageX-a(this).offset().left)/a(this).width()*100+"% "+(b.pageY-a(this).offset().top)/a(this).height()*100+"%"})});a("#carousel-gallery-detail .item").on("mousemove",function(b){a(this).find("img").css({"transform-origin":(b.pageX-a(this).offset().left)/a(this).width()*100+"% "+(b.pageY-a(this).offset().top)/a(this).height()*100+"%"})});a(".counters").appear(function(){a(".count_nums").countTo()});e=
(new Date).getFullYear();u=a("#year , #year1");2019===e?u.text(e):u.text("2019-"+e);e=a(".count_down");e.length&&e.downCount({date:"2/21/2021 12:00:00",offset:10});e=a("#pagepiling");a(e).length&&(a(e).pagepiling({onLeave:function(b,c,d){c=a("#pagepiling section:last").index();"down"===d?(a("#para-menu li a").removeClass("current"),a("#para-menu li").eq(b).children().addClass("current"),a(".para-btn.para-up").removeClass("disabled")):(b-=2,a("#para-menu li a").removeClass("current"),a("#para-menu li").eq(b).children().addClass("current"));
0===b?a(".para-btn.para-up").addClass("disabled"):c===b?a(".para-btn.para-down").addClass("disabled"):"up"===d&&b<c&&a(".para-btn.para-down").removeClass("disabled")}}),a(".para-up").on("click",function(){a.fn.pagepiling.moveSectionUp()}),a(".para-down").on("click",function(){a.fn.pagepiling.moveSectionDown()}));a("#para-menu li a").on("click",function(b){b.preventDefault();b=a(this).parent().index();var c=a("#pagepiling").find("section").length;b++;a.fn.pagepiling.moveTo(b);a("#para-menu li a").removeClass("current");
a(this).addClass("current");1===b?a(".para-btn.para-up").addClass("disabled"):b===c&&a(".para-btn.para-down").addClass("disabled")});a("#typed-text").length&&new Typed("#typed-text",{strings:["Front End Developer","Front End Designer","Front End Master","Creative Designer","Creative Builder"],typeSpeed:45,backSpeed:22,backDelay:1E3,smartBackspace:!0,loop:!0});a("#blog-measonry").cubeportfolio({layoutMode:"grid",defaultFilter:"*",animationType:"scaleSides",gapHorizontal:30,gapVertical:30,gridAdjustment:"responsive",
mediaQueries:[{width:1500,cols:3},{width:1100,cols:3},{width:992,cols:3},{width:768,cols:3},{width:480,cols:1},{width:320,cols:1}]});a("#services-measonry").cubeportfolio({layoutMode:"grid",defaultFilter:"*",filters:"#services-filter",animationType:"scaleSides",gapHorizontal:30,gapVertical:30,gridAdjustment:"responsive",mediaQueries:[{width:1500,cols:3},{width:1100,cols:3},{width:992,cols:3},{width:768,cols:2},{width:480,cols:1},{width:320,cols:1}]});a("#testimonial-grid").cubeportfolio({layoutMode:"grid",
defaultFilter:"*",animationType:"quicksand",gapHorizontal:0,gapVertical:0,gridAdjustment:"responsive",mediaQueries:[{width:1500,cols:4},{width:1100,cols:4},{width:800,cols:3},{width:480,cols:2},{width:320,cols:1}]});a("#price-grid").cubeportfolio({layoutMode:"grid",defaultFilter:"*",animationType:"quicksand",gapHorizontal:50,gapVertical:50,gridAdjustment:"responsive",mediaQueries:[{width:1500,cols:3},{width:1100,cols:3},{width:800,cols:2},{width:480,cols:1}]});a("#grid-mosaic").cubeportfolio({filters:"#mosaic-filter",
layoutMode:"grid",defaultFilter:"*",animationType:"rotateSides",gapHorizontal:0,gapVertical:0,gridAdjustment:"responsive",mediaQueries:[{width:1500,cols:3},{width:1100,cols:3},{width:767,cols:2},{width:480,cols:1}],plugins:{loadMore:{element:"#js-loadMore-mosaic",action:"click",loadItems:3}}});a("#rev_main").show().revolution({sliderType:"standard",jsFileLocation:"js/revolution/",sliderLayout:"fullscreen",dottedOverlay:"none",delay:9E3,navigation:{keyboardNavigation:"off",keyboard_direction:"horizontal",
mouseScrollNavigation:"off",mouseScrollReverse:"default",onHoverStop:"off",touch:{touchenabled:"on",swipe_threshold:75,swipe_min_touches:1,swipe_direction:"horizontal",drag_block_vertical:!1},bullets:{enable:!0,hide_onmobile:!0,style:"numbered",hide_onleave:!1,hide_under:767,direction:"vertical",h_align:"left",v_align:"center",h_offset:20,v_offset:0,space:5,tmp:'<div class="tp-bullet-number"><span class="tp-count">{{param1}}</span><span class="tp-bullet-line"></span></div>'},arrows:{style:"",enable:!1}},
viewPort:{enable:!0,outof:"pause",visible_area:"80%",presize:!1},responsiveLevels:[1240,1024,778,480],visibilityLevels:[1240,1024,778,480],gridwidth:[1140,1024,768,480],gridheight:[660,650,600,490],lazyType:"none",parallax:{type:"mouse",origo:"slidercenter",speed:2E3,speedbg:0,speedls:0,levels:[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20,25,55],disable_onmobile:"on"},shadow:0,spinner:"off",stopLoop:"off",stopAfterLoops:-1,stopAtSlide:-1,shuffle:"off",autoHeight:"off",hideThumbsOnMobile:"off",hideSliderAtLimit:0,
hideCaptionAtLimit:0,hideAllCaptionAtLimit:0,debugMode:!1,fallbacks:{simplifyAll:"off",nextSlideOnWindowFocus:"off",disableFocusListener:!1}});a("#rev_arrows").show().revolution({sliderType:"standard",jsFileLocation:"js/revolution/",sliderLayout:"fullscreen",autoHeight:"off",dottedOverlay:"none",delay:9E3,navigation:{keyboardNavigation:"off",keyboard_direction:"horizontal",mouseScrollNavigation:"off",mouseScrollReverse:"default",onHoverStop:"on",touch:{touchenabled:"on",swipe_threshold:75,swipe_min_touches:1,
swipe_direction:"horizontal",drag_block_vertical:!1},arrows:{style:"zeus",enable:!0,hide_onmobile:!0,hide_under:600,hide_onleave:!0,hide_delay:200,hide_delay_mobile:1200,tmp:'<div class="tp-title-wrap"> <div class="tp-arr-imgholder"></div> </div>',left:{h_align:"left",v_align:"center",h_offset:30,v_offset:0},right:{h_align:"right",v_align:"center",h_offset:30,v_offset:0}}},viewPort:{enable:!0,outof:"pause",visible_area:"80%",presize:!1},responsiveLevels:[1240,1024,778,480],visibilityLevels:[1240,
1024,778,480],gridwidth:[1140,1024,768,480],gridheight:[668,650,600,490],lazyType:"none",parallax:{type:"mouse",origo:"slidercenter",speed:2E3,speedbg:0,speedls:0,levels:[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20,25,55],disable_onmobile:"on"},shadow:0,spinner:"off",stopLoop:"off",stopAfterLoops:-1,stopAtSlide:-1,shuffle:"off",hideThumbsOnMobile:"off",hideSliderAtLimit:0,hideCaptionAtLimit:0,hideAllCaptionAtLilmit:0,debugMode:!1,fallbacks:{simplifyAll:"off",nextSlideOnWindowFocus:"off",disableFocusListener:!1}});
(new a("#rev_interactive")).show().revolution({sliderType:"carousel",jsFileLocation:"js/revolution/",sliderLayout:"fullscreen",dottedOverlay:"none",delay:9E3,navigation:{keyboardNavigation:"off",keyboard_direction:"horizontal",mouseScrollNavigation:"off",mouseScrollReverse:"default",onHoverStop:"off",touch:{touchenabled:"on",swipe_threshold:75,swipe_min_touches:1,swipe_direction:"horizontal",drag_block_vertical:!1},bullets:{style:"",enable:!0,hide_onmobile:!0,hide_under:480,hide_onleave:!1,hide_delay:200,
direction:"horizontal",space:10,h_align:"center",v_align:"bottom",h_offset:0,v_offset:30},arrows:{style:"",enable:!1}},viewPort:{enable:!0,outof:"pause",visible_area:"80%",presize:!1},responsiveLevels:[1240,1024,778,480],visibilityLevels:[1240,1024,778,480],gridwidth:[1140,1024,768,480],gridheight:[660,650,600,490],lazyType:"none",parallax:{type:"mouse",origo:"slidercenter",speed:2E3,speedbg:0,speedls:0,levels:[2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,20,25,55],disable_onmobile:"on"},shadow:0,spinner:"off",
stopLoop:"off",stopAfterLoops:-1,stopAtSlide:-1,shuffle:"off",autoHeight:"off",hideThumbsOnMobile:"off",hideSliderAtLimit:0,hideCaptionAtLimit:0,hideAllCaptionAtLimit:0,debugMode:!1,fallbacks:{simplifyAll:"off",nextSlideOnWindowFocus:"off",disableFocusListener:!1}}).on("revolution.slide.onchange",function(b,c){var d=c.slideIndex;d--;a(".tp-bullets").find(".tp-bullet").eq(d).addClass("active").siblings().removeClass("active");setTimeout(function(){a(".tp-bullets").find(".tp-bullet").eq(d).addClass("selected").siblings().removeClass("selected")},
300)});a("#rev_single").show().revolution({sliderType:"hero",jsFileLocation:"js/revolution",sliderLayout:"fullscreen",scrollbarDrag:"true",dottedOverlay:"none",delay:9E3,navigation:{},responsiveLevels:[1240,1024,778,480],visibilityLevels:[1240,1024,778,480],gridwidth:[1170,1024,778,480],gridheight:[868,768,960,720],lazyType:"none",parallax:{type:"scroll",origo:"slidercenter",speed:400,levels:[10,15,20,25,30,35,40,-10,-15,-20,-25,-30,-35,-40,-45,55]},shadow:0,spinner:"off",autoHeight:"off",fullScreenAutoWidth:"off",
fullScreenAlignForce:"off",fullScreenOffsetContainer:"",disableProgressBar:"on",hideThumbsOnMobile:"off",hideSliderAtLimit:0,hideCaptionAtLimit:0,hideAllCaptionAtLilmit:0,debugMode:!1,fallbacks:{simplifyAll:"off",disableFocusListener:!1}});a("#rev_creative").show().revolution({sliderType:"standard",sliderLayout:"fullscreen",scrollbarDrag:"true",dottedOverlay:"none",navigation:{keyboardNavigation:"off",keyboard_direction:"horizontal",mouseScrollNavigation:"off",bullets:{style:"",enable:!0,rtl:!1,hide_onmobile:!1,
hide_onleave:!1,hide_under:767,hide_over:9999,tmp:"",direction:"horizontal",space:10,h_align:"center",v_align:"bottom",h_offset:0,v_offset:40},arrows:{enable:!1,hide_onmobile:!0,hide_onleave:!1,hide_under:767,left:{h_align:"left",v_align:"center",h_offset:20,v_offset:30},right:{h_align:"right",v_align:"center",h_offset:20,v_offset:30}},touch:{touchenabled:"on",swipe_threshold:75,swipe_min_touches:1,swipe_direction:"horizontal",drag_block_vertical:!1}},viewPort:{enable:!0,outof:"pause",visible_area:"90%"},
responsiveLevels:[4096,1024,778,480],gridwidth:[1140,1024,750,480],gridheight:[600,500,500,350],lazyType:"none",parallax:{type:"mouse",origo:"slidercenter",speed:9E3,levels:[2,3,4,5,6,7,12,16,10,50]},shadow:0,spinner:"off",stopLoop:"off",stopAfterLoops:-1,stopAtSlide:-1,shuffle:"off",autoHeight:"off",hideThumbsOnMobile:"off",hideSliderAtLimit:0,hideCaptionAtLimit:0,disableProgressBar:"off",hideAllCaptionAtLilmit:0,debugMode:!1,fallbacks:{simplifyAll:"off",nextSlideOnWindowFocus:"off",disableFocusListener:!1}});
a("#rev_one_page").show().revolution({sliderType:"standard",sliderLayout:"fullscreen",scrollbarDrag:"true",dottedOverlay:"none",navigation:{keyboardNavigation:"off",keyboard_direction:"horizontal",mouseScrollNavigation:"off",bullets:{style:"",enable:!0,rtl:!1,hide_onmobile:!1,hide_onleave:!1,hide_under:767,hide_over:9999,tmp:"",direction:"vertical",space:10,h_align:"right",v_align:"center",h_offset:40,v_offset:0},arrows:{enable:!1,hide_onmobile:!0,hide_onleave:!1,hide_under:767,left:{h_align:"left",
v_align:"center",h_offset:20,v_offset:30},right:{h_align:"right",v_align:"center",h_offset:20,v_offset:30}},touch:{touchenabled:"on",swipe_threshold:75,swipe_min_touches:1,swipe_direction:"horizontal",drag_block_vertical:!1}},viewPort:{enable:!0,outof:"pause",visible_area:"90%"},responsiveLevels:[4096,1024,778,480],gridwidth:[1140,1024,750,480],gridheight:[600,500,500,350],lazyType:"none",parallax:{type:"mouse",origo:"slidercenter",speed:9E3,levels:[2,3,4,5,6,7,12,16,10,50]},shadow:0,spinner:"off",
stopLoop:"off",stopAfterLoops:-1,stopAtSlide:-1,shuffle:"off",autoHeight:"off",hideThumbsOnMobile:"off",hideSliderAtLimit:0,hideCaptionAtLimit:0,disableProgressBar:"off",hideAllCaptionAtLilmit:0,debugMode:!1,fallbacks:{simplifyAll:"off",nextSlideOnWindowFocus:"off",disableFocusListener:!1}});a("#rev_slider_8_1").show().revolution({sliderType:"standard",jsFileLocation:"//localhost/revslider/revslider/public/assets/js/",sliderLayout:"fullscreen",dottedOverlay:"none",delay:9E3,navigation:{keyboardNavigation:"off",
keyboard_direction:"horizontal",mouseScrollNavigation:"off",mouseScrollReverse:"default",onHoverStop:"on",touch:{touchenabled:"on",touchOnDesktop:"off",swipe_threshold:75,swipe_min_touches:50,swipe_direction:"horizontal",drag_block_vertical:!1},arrows:{style:"uranus",enable:!0,hide_onmobile:!0,hide_under:600,hide_onleave:!0,hide_delay:200,hide_delay_mobile:1200,tmp:'<div class="hvr-pulse"></div>',left:{h_align:"left",v_align:"center",h_offset:30,v_offset:0},right:{h_align:"right",v_align:"center",
h_offset:30,v_offset:0}},bullets:{enable:!0,hide_onmobile:!0,hide_under:600,style:"hephaistos",hide_onleave:!0,hide_delay:200,hide_delay_mobile:1200,direction:"horizontal",h_align:"center",v_align:"bottom",h_offset:0,v_offset:30,space:5,tmp:""}},responsiveLevels:[1240,1024,778,480],visibilityLevels:[1240,1024,778,480],gridwidth:[1240,1024,778,480],gridheight:[868,600,500,400],lazyType:"smart",parallax:{type:"mouse",origo:"slidercenter",speed:2E3,speedbg:0,speedls:0,levels:[2,3,4,5,6,7,12,16,10,50,
10,11,12,13,14,55]},shadow:0,spinner:"off",stopLoop:"off",stopAfterLoops:-1,stopAtSlide:-1,shuffle:"off",autoHeight:"off",fullScreenAutoWidth:"off",fullScreenAlignForce:"off",fullScreenOffsetContainer:"",fullScreenOffset:"",hideThumbsOnMobile:"off",hideSliderAtLimit:0,hideCaptionAtLimit:0,hideAllCaptionAtLilmit:0,debugMode:!1,fallbacks:{simplifyAll:"off",nextSlideOnWindowFocus:"off",disableFocusListener:!1}});a("#vertical-bullets").show().revolution({sliderType:"standard",sliderLayout:"fullscreen",
scrollbarDrag:"true",dottedOverlay:"none",navigation:{keyboardNavigation:"off",keyboard_direction:"horizontal",mouseScrollNavigation:"off",mouseScrollReverse:"default",onHoverStop:"off",bullets:{enable:!0,hide_onmobile:!0,hide_under:767,hide_onleave:!1,direction:"vertical",h_align:"left",v_align:"center",h_offset:30,v_offset:0,space:5,tmp:'<div class="tp-bullet-inner"></div><div class="tp-line"></div>'},touch:{touchenabled:"on",swipe_threshold:75,swipe_min_touches:1,swipe_direction:"horizontal",drag_block_vertical:!1}},
viewPort:{enable:!0,outof:"pause",visible_area:"90%",presize:!0},responsiveLevels:[4096,1200,778,480],gridwidth:[1140,1024,750,480],gridheight:[600,500,500,350],lazyType:"none",parallax:{type:"mouse",origon:"slidercenter",speed:9E3,levels:[2,3,4,5,6,7,12,16,10,50]},shadow:0,spinner:"off",stopLoop:"off",stopAfterLoops:-1,stopAtSlide:-1,shuffle:"off",autoHeight:"off",hideThumbsOnMobile:"off",hideSliderAtLimit:0,hideCaptionAtLimit:360,hideAllCaptionAtLilmit:360,debugMode:!1,fallbacks:{simplifyAll:"off",
nextSlideOnWindowFocus:"off",disableFocusListener:!1}})});
